FROM node:18-alpine as build

WORKDIR /Sneakers

COPY Frontend/package*.json ./

RUN npm install

COPY Frontend/ ./

RUN npm run build

FROM nginx:alpine

COPY --from=build /Sneakers/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]